### ISSUE TITLE
PHP 5.4 and ZfcDatagrid

### ISSUE THREAD

**Issue by shinesoftware** [ThaDafinser/ZfcDatagrid#213]
Hello,

how have I to use your datagrid with the php 5.4?

thanks

**Comment by ThaDafinser** [comment]
@shinesoftware you *should* still be able to use it with 5.4, but it's not supported anymore by ZfcDatagrid and PHP http://php.net/eol.php

The last version for composer is https://github.com/ThaDafinser/ZfcDatagrid/blob/0.11.0/composer.json

In theory you can still use master or the latest tag, since we did not make any special use from 5.5 or 5.6. But there could be changed in the future which will break it in 5.4, since it's not active tested anymore

**Comment by shinesoftware** [comment]
the 0.11.0 version is View/Helper/TableRow.php array issue affected.

**Comment by ThaDafinser** [comment]
@shinesoftware i think the only possibility is to fork it currently (like you already did).

Since latest ZF2 version also requires PHP 5.5 i think it's not a good idea, to open ZfcDatagrid for 5.4
Since it will then not be tested, i dont have a good feeling.

https://github.com/zendframework/zf2/blob/release-2.5.2/composer.json#L12
