### ISSUE TITLE
Disable cache

### ISSUE THREAD

**Issue by manuscle** [ThaDafinser/ZfcDatagrid#269]
How i can disable cache with ZfcDatagrid?

**Comment by ThaDafinser** [comment]
@manuscle i'm afraid you cant - otherwise the export won't work anymore (PDF/Excel).

But if you don't use export, you could at least use the `Memory` adapter
https://github.com/zendframework/zend-cache/blob/release-2.7.2/src/Storage/Adapter/Memory.php

I haven't found a `null` adapter yet, like it's provided at Doctrine Cache
https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/VoidCache.php

**Comment by buliq** [comment]
How about BlackHole adapter?

**Comment by kokspflanze** [comment]
you can also disable the export function, i think than was the cache disabled too.

**Comment by manuscle** [comment]
ZfcDatagrid Should let users choose if they want to use cache or not. Some of custom features are not "cacheable" and make App throwing an exception.

**Comment by ThaDafinser** [comment]
You can "disable" the cache by using the Memory or BlackHole cache.
https://github.com/zendframework/zend-cache/blob/master/src/Storage/Adapter/BlackHole.php
https://github.com/zendframework/zend-cache/blob/master/src/Storage/Adapter/Memory.php

What kind of features do not work?

**Comment by manuscle** [comment]
I try to use Memory cache but i get an error when i try to export in phpExcel: 'Sort conditions from cache are missing!'
When i back to FileSystem cache i get the same error.

**Comment by ThaDafinser** [comment]
@manuscle what version do you use?
This (should be) resolved with https://github.com/ThaDafinser/ZfcDatagrid/pull/197/files

This message is not anymore in the code.

**Comment by manuscle** [comment]
Oh sorry i have to update ZF first, that's why i don't have the latest ZfcDatagrid ...

**Comment by ThaDafinser** [comment]
This issue was moved to zfc-datagrid/zfc-datagrid#34
